# Generated by Django 3.1.3 on 2021-04-09 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formulacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('codigo', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
                ('anio', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name_plural': 'Publicaciones',
            },
        ),
        migrations.CreateModel(
            name='MovimientoGasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('anio', models.CharField(max_length=4)),
                ('periodo', models.CharField(max_length=2)),
                ('tipo_movimiento', models.IntegerField(choices=[(1, 'Modificacion'), (2, 'Contrato'), (3, 'Ordenpago'), (4, 'Compromiso')])),
                ('monto', models.DecimalField(decimal_places=4, max_digits=22)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_gastos', to='formulacion.partidaaccioninterna')),
            ],
            options={
                'verbose_name_plural': 'Movimientos de Gastos',
            },
        ),
    ]
