# Generated by Django 3.1.3 on 2020-12-03 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='nucleo.modulo', verbose_name='Modulo')),
            ],
        ),
    ]
