# Generated by Django 3.1.3 on 2021-04-09 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnticipoContrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('anio', models.CharField(max_length=4)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=22)),
            ],
            options={
                'verbose_name_plural': 'Anticipos de Contratos',
            },
        ),
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('rif', models.CharField(max_length=12)),
                ('razon_social', models.CharField(max_length=100)),
                ('siglas', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=500)),
                ('telefono', models.CharField(max_length=13)),
                ('correo', models.EmailField(max_length=254)),
                ('numero_inscripcion', models.IntegerField()),
                ('fecha_inscripcion', models.DateField()),
                ('numero_registro', models.CharField(max_length=12)),
                ('fecha_registro', models.DateField()),
                ('capital', models.DecimalField(decimal_places=4, max_digits=22)),
                ('representante', models.CharField(max_length=100)),
                ('cedula_representante', models.CharField(max_length=12)),
                ('fecha_vigencia', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Beneficiarios',
            },
        ),
        migrations.CreateModel(
            name='BeneficiarioContrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'verbose_name_plural': 'Beneficiarios de Contratos',
            },
        ),
        migrations.CreateModel(
            name='Compromiso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('anio', models.CharField(max_length=4)),
                ('fecha', models.DateField()),
                ('periodo', models.CharField(max_length=2)),
                ('numero', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Afectaciones Presupuestarias',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('anio', models.CharField(max_length=4)),
                ('codigo', models.CharField(max_length=6)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=300)),
                ('monto', models.DecimalField(decimal_places=4, max_digits=22)),
                ('saldo', models.DecimalField(decimal_places=4, max_digits=22)),
                ('monto_transito', models.DecimalField(decimal_places=4, max_digits=22)),
                ('cedula_responsable', models.CharField(max_length=12)),
                ('nombre_responsable', models.CharField(max_length=100)),
                ('anticipo', models.BooleanField(default=False)),
                ('porcentaje_anticipo', models.FloatField(null=True)),
                ('valuacion', models.BooleanField(default=False)),
                ('cantidad_valuacion', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Contratos',
            },
        ),
        migrations.CreateModel(
            name='ContratoPartida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('anio', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name_plural': 'Partidas de Contratos',
            },
        ),
        migrations.CreateModel(
            name='DetalleDocumentoPagar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('item', models.IntegerField()),
                ('denominacion', models.CharField(max_length=300)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=22)),
                ('total', models.DecimalField(decimal_places=4, max_digits=22)),
                ('contador', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Detalles de Documentos a Pagar',
            },
        ),
        migrations.CreateModel(
            name='DocumentoPagar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('anio', models.CharField(max_length=4)),
                ('numero', models.CharField(max_length=10)),
                ('numero_control', models.CharField(max_length=10)),
                ('fecha', models.DateField()),
                ('monto_imponible', models.DecimalField(decimal_places=4, max_digits=22)),
                ('monto_iva', models.DecimalField(decimal_places=4, max_digits=22)),
                ('monto', models.DecimalField(decimal_places=4, max_digits=22)),
                ('descripcion', models.CharField(max_length=100)),
                ('forma_pago', models.IntegerField(choices=[(1, 'Crédito'), (2, 'Contado'), (3, 'Efectivo')], default=1)),
            ],
            options={
                'verbose_name_plural': 'Documentos a Pagar',
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('anio', models.CharField(max_length=4)),
                ('codigo', models.CharField(max_length=6)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=300)),
                ('monto', models.DecimalField(decimal_places=4, max_digits=22)),
                ('saldo', models.DecimalField(decimal_places=4, max_digits=22)),
                ('monto_transito', models.DecimalField(decimal_places=4, max_digits=22)),
                ('estatus', models.IntegerField(choices=[(0, 'Elaborada'), (1, 'Verificada'), (2, 'Anulada'), (3, 'Pagada'), (4, 'Reversada')], default=0, verbose_name='Estatus Orden')),
            ],
            options={
                'verbose_name_plural': 'Ordenes',
            },
        ),
        migrations.CreateModel(
            name='TipoBeneficiario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('abreviacion', models.CharField(max_length=3)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Beneficiarios',
            },
        ),
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('codigo', models.CharField(max_length=3)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Contratos',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('codigo', models.CharField(max_length=4)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Documentos',
            },
        ),
        migrations.CreateModel(
            name='TipoOrden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('codigo', models.CharField(max_length=3)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Ordenes',
            },
        ),
        migrations.CreateModel(
            name='ValuacionContrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('anio', models.CharField(max_length=4)),
                ('numero', models.IntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=22)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='valuaciones_contratos', to='compras.contrato')),
            ],
            options={
                'verbose_name_plural': 'Valuaciones de Contratos',
            },
        ),
    ]
