# Generated by Django 3.1.3 on 2021-03-05 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formulacion', '0001_initial'),
        ('contabilidad', '0001_initial'),
        ('tesoreria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('rif', models.CharField(max_length=12)),
                ('razon_social', models.CharField(max_length=100)),
                ('siglas', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=500)),
                ('telefono', models.CharField(max_length=13)),
                ('correo', models.EmailField(max_length=254)),
                ('numero_inscripcion', models.IntegerField()),
                ('fecha_inscripcion', models.DateField()),
                ('numero_registro', models.CharField(max_length=12)),
                ('fecha_registro', models.DateField()),
                ('capital', models.DecimalField(decimal_places=4, max_digits=22)),
                ('representante', models.CharField(max_length=100)),
                ('cedula_representante', models.CharField(max_length=12)),
                ('fecha_vigencia', models.DateField()),
                ('cuenta_anticipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anticipo_beneficiarios', to='contabilidad.cuentacontable')),
                ('cuenta_contable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuenta_beneficiarios', to='contabilidad.cuentacontable')),
                ('parroquia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beneficiarios', to='formulacion.parroquia')),
            ],
            options={
                'verbose_name_plural': 'Beneficiarios',
            },
        ),
        migrations.CreateModel(
            name='Compromiso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('anio', models.CharField(max_length=4)),
                ('codigo', models.CharField(max_length=6)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=300)),
                ('monto', models.DecimalField(decimal_places=4, max_digits=22)),
                ('saldo', models.DecimalField(decimal_places=4, max_digits=22)),
                ('monto_transito', models.DecimalField(decimal_places=4, max_digits=22)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compromisos', to='compras.beneficiario')),
            ],
            options={
                'verbose_name_plural': 'Compromisos',
            },
        ),
        migrations.CreateModel(
            name='TipoCompromiso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('codigo', models.CharField(max_length=3)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Compromisos',
            },
        ),
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('codigo', models.CharField(max_length=3)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Contratos',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('codigo', models.CharField(max_length=4)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Documentos',
            },
        ),
        migrations.CreateModel(
            name='TipoBeneficiario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('abreviacion', models.CharField(max_length=3)),
                ('descripcion', models.CharField(max_length=100)),
                ('cuenta_contable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipos_beneficiarios', to='contabilidad.cuentacontable')),
            ],
            options={
                'verbose_name_plural': 'Tipos de Beneficiarios',
            },
        ),
        migrations.CreateModel(
            name='DocumentoPagar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('anio', models.CharField(max_length=4)),
                ('numero', models.CharField(max_length=10)),
                ('numero_control', models.CharField(max_length=10)),
                ('fecha', models.DateField()),
                ('monto_imponible', models.DecimalField(decimal_places=4, max_digits=22)),
                ('monto_iva', models.DecimalField(decimal_places=4, max_digits=22)),
                ('monto', models.DecimalField(decimal_places=4, max_digits=22)),
                ('descripcion', models.CharField(max_length=100)),
                ('forma_pago', models.IntegerField(choices=[(1, 'Crédito'), (2, 'Contado'), (3, 'Efectivo')], default=1)),
                ('beneficiario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_pagar', to='compras.beneficiario')),
                ('compromiso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_pagar', to='compras.compromiso')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_pagar', to='compras.tipodocumento')),
            ],
            options={
                'verbose_name_plural': 'Documentos a Pagar',
                'unique_together': {('numero', 'anio', 'beneficiario')},
            },
        ),
        migrations.CreateModel(
            name='DetalleDocumentoPagar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('item', models.IntegerField()),
                ('denominacion', models.CharField(max_length=300)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=22)),
                ('total', models.DecimalField(decimal_places=4, max_digits=22)),
                ('contador', models.IntegerField(default=1)),
                ('documento_pagar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_documentos_pagar', to='compras.documentopagar')),
            ],
            options={
                'verbose_name_plural': 'Detalles de Documentos a Pagar',
            },
        ),
        migrations.CreateModel(
            name='CuentaBeneficiario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('numero', models.CharField(max_length=20)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuenta_beneficiarios', to='tesoreria.banco')),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuenta_beneficiarios', to='compras.beneficiario')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuenta_beneficiarios', to='tesoreria.tipocuenta')),
            ],
            options={
                'verbose_name_plural': 'Cuentas Bancarias de Beneficiarios',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('anio', models.CharField(max_length=4)),
                ('codigo', models.CharField(max_length=6)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=300)),
                ('monto', models.DecimalField(decimal_places=4, max_digits=22)),
                ('saldo', models.DecimalField(decimal_places=4, max_digits=22)),
                ('monto_transito', models.DecimalField(decimal_places=4, max_digits=22)),
                ('cedula_responsable', models.CharField(max_length=12)),
                ('nombre_responsable', models.CharField(max_length=100)),
                ('addendum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='compras.contrato')),
                ('tipo_contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='compras.tipocontrato')),
            ],
            options={
                'verbose_name_plural': 'Contratos',
            },
        ),
        migrations.AddField(
            model_name='compromiso',
            name='tipo_compromiso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compromisos', to='compras.tipocompromiso'),
        ),
        migrations.CreateModel(
            name='BeneficiarioContrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beneficiarios_contratos', to='compras.beneficiario')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beneficiarios_contratos', to='compras.contrato')),
            ],
            options={
                'verbose_name_plural': 'Beneficiarios de Contratos',
            },
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='tipo_beneficiario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beneficiarios', to='compras.tipobeneficiario'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='usuario_inscripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beneficiarios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PartidaContrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('anio', models.CharField(max_length=4)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidas_contratos', to='compras.contrato')),
                ('partida_accioninterna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidas_contratos', to='formulacion.partidaaccioninterna')),
            ],
            options={
                'verbose_name_plural': 'Beneficiarios de Contratos',
                'unique_together': {('partida_accioninterna', 'anio')},
            },
        ),
    ]
