# Generated by Django 3.1.3 on 2021-02-23 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
        ('formulacion', '__first__'),
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipobeneficiario',
            name='cuenta_contable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipos_beneficiarios', to='contabilidad.cuentacontable'),
        ),
        migrations.AddField(
            model_name='partidacontrato',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidas_contratos', to='compras.contrato'),
        ),
        migrations.AddField(
            model_name='partidacontrato',
            name='partida_accioninterna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidas_contratos', to='formulacion.partidaaccioninterna'),
        ),
        migrations.AddField(
            model_name='documentopagar',
            name='compromiso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_pagar', to='compras.compromiso'),
        ),
        migrations.AddField(
            model_name='documentopagar',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_pagar', to='compras.tipodocumento'),
        ),
        migrations.AddField(
            model_name='detalledocumentopagar',
            name='documento_pagar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_documentos_pagar', to='compras.documentopagar'),
        ),
    ]
