# Generated by Django 3.1.3 on 2021-03-04 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentopagar',
            name='beneficiario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_pagar', to='compras.beneficiario'),
        ),
        migrations.AlterUniqueTogether(
            name='documentopagar',
            unique_together={('numero', 'anio', 'beneficiario')},
        ),
    ]
