# Generated by Django 3.1.3 on 2021-04-09 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contabilidad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compras', '0001_initial'),
        ('ejecucion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuacioncontrato',
            name='orden_pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='valuaciones_contratos', to='ejecucion.ordenpago'),
        ),
        migrations.AddField(
            model_name='tipobeneficiario',
            name='cuenta_contable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipos_beneficiarios', to='contabilidad.cuentacontable'),
        ),
        migrations.AddField(
            model_name='orden',
            name='anulador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='anulador_ordenes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orden',
            name='beneficiario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='compras.beneficiario'),
        ),
        migrations.AddField(
            model_name='orden',
            name='elaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elaborador_ordenes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orden',
            name='orden_pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='ejecucion.ordenpago'),
        ),
        migrations.AddField(
            model_name='orden',
            name='reversor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisor_ordenes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orden',
            name='tipo_orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='compras.tipoorden'),
        ),
        migrations.AddField(
            model_name='orden',
            name='verificador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verificador_ordenes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentopagar',
            name='beneficiario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_pagar', to='compras.beneficiario'),
        ),
        migrations.AddField(
            model_name='documentopagar',
            name='orden',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_pagar', to='compras.orden'),
        ),
        migrations.AddField(
            model_name='documentopagar',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_pagar', to='compras.tipodocumento'),
        ),
        migrations.AddField(
            model_name='detalledocumentopagar',
            name='documento_pagar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_documentos_pagar', to='compras.documentopagar'),
        ),
        migrations.AddField(
            model_name='contratopartida',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_partidas', to='compras.contrato'),
        ),
    ]
