# Generated by Django 3.1.3 on 2021-03-22 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ejecucion', '0001_initial'),
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiario',
            name='parroquia',
        ),
        migrations.AddField(
            model_name='compromiso',
            name='orden_pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compromisos', to='ejecucion.ordenpago'),
        ),
        migrations.DeleteModel(
            name='CuentaBeneficiario',
        ),
    ]
