# Generated by Django 3.1.3 on 2021-02-23 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formulacion', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contabilidad', '0002_auto_20210223_1832'),
        ('compras', '0002_auto_20210223_1832'),
        ('tesoreria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentabeneficiario',
            name='banco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuenta_beneficiarios', to='tesoreria.banco'),
        ),
        migrations.AddField(
            model_name='cuentabeneficiario',
            name='beneficiario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuenta_beneficiarios', to='compras.beneficiario'),
        ),
        migrations.AddField(
            model_name='cuentabeneficiario',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuenta_beneficiarios', to='tesoreria.tipocuenta'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='addendum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='compras.contrato'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='tipo_contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='compras.tipocontrato'),
        ),
        migrations.AddField(
            model_name='compromiso',
            name='beneficiario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compromisos', to='compras.beneficiario'),
        ),
        migrations.AddField(
            model_name='compromiso',
            name='tipo_compromiso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compromisos', to='compras.tipocompromiso'),
        ),
        migrations.AddField(
            model_name='beneficiariocontrato',
            name='beneficiario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beneficiarios_contratos', to='compras.beneficiario'),
        ),
        migrations.AddField(
            model_name='beneficiariocontrato',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beneficiarios_contratos', to='compras.contrato'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='cuenta_anticipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anticipo_beneficiarios', to='contabilidad.cuentacontable'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='cuenta_contable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuenta_beneficiarios', to='contabilidad.cuentacontable'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='parroquia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beneficiarios', to='formulacion.parroquia'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='tipo_beneficiario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beneficiarios', to='compras.tipobeneficiario'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='usuario_inscripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beneficiarios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='partidacontrato',
            unique_together={('partida_accioninterna', 'anio')},
        ),
    ]
