# Generated by Django 3.1.3 on 2021-03-02 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formulacion', '0001_initial'),
        ('contabilidad', '0001_initial'),
        ('ejecucion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('codigo', models.CharField(max_length=3)),
                ('nombre_corto', models.CharField(max_length=20)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('rif', models.CharField(max_length=12)),
                ('direccion', models.CharField(max_length=500)),
                ('codigo_postal', models.CharField(max_length=5)),
                ('persona_contacto', models.CharField(max_length=100)),
                ('telefono_contacto', models.CharField(max_length=13)),
                ('correo', models.EmailField(max_length=254)),
                ('fax', models.CharField(max_length=12)),
                ('condicion', models.BooleanField(default=True)),
                ('cuenta_contable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bancos', to='contabilidad.cuentacontable')),
                ('parroquia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bancos', to='formulacion.parroquia')),
            ],
            options={
                'verbose_name_plural': 'Bancos',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('descripcion', models.CharField(max_length=300)),
                ('cuenta_contable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='contabilidad.cuentacontable')),
            ],
            options={
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.CreateModel(
            name='TipoCuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('codigo', models.CharField(max_length=2)),
                ('descripcion', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Cuentas Bancarias',
            },
        ),
        migrations.CreateModel(
            name='TipoImpuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('porcentaje', models.DecimalField(decimal_places=4, max_digits=22)),
                ('descripcion', models.CharField(max_length=300)),
                ('indicador_iva', models.BooleanField(default=False)),
                ('cuenta_contable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipos_impuestos', to='contabilidad.cuentacontable')),
            ],
            options={
                'verbose_name_plural': 'Tipos de Impuestos',
            },
        ),
        migrations.CreateModel(
            name='RetencionDeduccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('monto', models.DecimalField(decimal_places=4, max_digits=22)),
                ('saldo', models.DecimalField(decimal_places=4, max_digits=22)),
                ('orden_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retenciones_deducciones', to='ejecucion.ordenpago')),
                ('pago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retenciones_deducciones', to='tesoreria.pago')),
                ('tipo_impuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retenciones_deducciones', to='tesoreria.tipoimpuesto')),
            ],
            options={
                'verbose_name_plural': 'Retenciones y Deducciones',
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('numero', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=500)),
                ('codigo_postal', models.CharField(max_length=5)),
                ('telefono', models.CharField(max_length=13)),
                ('correo', models.EmailField(max_length=254)),
                ('repr_legal', models.CharField(max_length=100)),
                ('rif_repr_legal', models.CharField(max_length=12)),
                ('saldo_ultima_conc', models.DecimalField(decimal_places=4, max_digits=22)),
                ('fecha_ultima_conc', models.DateField()),
                ('saldo_conc_proceso', models.DecimalField(decimal_places=4, max_digits=22)),
                ('fecha_conc_proceso', models.DateField()),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas', to='tesoreria.banco')),
                ('cuenta_contable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas', to='contabilidad.cuentacontable')),
                ('parroquia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas', to='formulacion.parroquia')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas', to='tesoreria.tipocuenta')),
            ],
            options={
                'verbose_name_plural': 'Cuentas Bancarias',
            },
        ),
    ]
