# Generated by Django 3.1.3 on 2021-02-08 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formulacion', '0018_auto_20210208_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('codigo', models.CharField(max_length=3)),
                ('nombre_corto', models.CharField(max_length=20)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('rif', models.CharField(max_length=12)),
                ('direccion', models.CharField(max_length=500)),
                ('codigo_postal', models.CharField(max_length=5)),
                ('persona_contacto', models.CharField(max_length=100)),
                ('telefono_contacto', models.CharField(max_length=13)),
                ('correo', models.EmailField(max_length=254)),
                ('fax', models.CharField(max_length=12)),
                ('condicion', models.BooleanField(default=True)),
                ('parroquia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bancos', to='formulacion.parroquia')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bancos', to='formulacion.partida')),
            ],
            options={
                'verbose_name_plural': 'Bancos',
            },
        ),
        migrations.CreateModel(
            name='TipoCuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('codigo', models.CharField(max_length=2)),
                ('descripcion', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Cuentas Bancarias',
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('numero', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=500)),
                ('codigo_postal', models.CharField(max_length=5)),
                ('telefono', models.CharField(max_length=13)),
                ('correo', models.EmailField(max_length=254)),
                ('repr_legal', models.CharField(max_length=100)),
                ('rif_repr_legal', models.CharField(max_length=12)),
                ('saldo_ultima_conc', models.DecimalField(decimal_places=4, max_digits=22)),
                ('fecha_ultima_conc', models.DateField()),
                ('saldo_conc_proceso', models.DecimalField(decimal_places=4, max_digits=22)),
                ('fecha_conc_proceso', models.DateField()),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas', to='tesoreria.banco')),
                ('parroquia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas', to='formulacion.parroquia')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas', to='formulacion.partida')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas', to='tesoreria.tipocuenta')),
            ],
            options={
                'verbose_name_plural': 'Cuentas Bancarias',
            },
        ),
    ]
