# Generated by Django 3.1.3 on 2021-01-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='eliminado',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
