# Generated by Django 3.1.3 on 2020-12-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0002_opcion'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name_plural': 'Perfiles'},
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={'verbose_name_plural': 'Roles'},
        ),
        migrations.RemoveField(
            model_name='rol',
            name='modulo',
        ),
        migrations.AddField(
            model_name='rol',
            name='opciones',
            field=models.ManyToManyField(related_name='roles', to='nucleo.Opcion', verbose_name='Opciones Disponibles'),
        ),
    ]
