# Generated by Django 3.1.3 on 2021-04-09 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfectacionContrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('anio', models.CharField(max_length=4)),
                ('fecha', models.DateField()),
                ('periodo', models.CharField(max_length=2)),
                ('numero', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Afectaciones a Contratos',
            },
        ),
        migrations.CreateModel(
            name='AfectacionPresupuestaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('anio', models.CharField(max_length=4)),
                ('fecha', models.DateField()),
                ('periodo', models.CharField(max_length=2)),
                ('numero', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Afectaciones Presupuestarias',
            },
        ),
        migrations.CreateModel(
            name='ClaseOrdenPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Clases de Ordenes de Pagos',
            },
        ),
        migrations.CreateModel(
            name='TipoOrdenPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('codigo', models.CharField(max_length=3)),
                ('descripcion', models.CharField(max_length=100)),
                ('compromete', models.BooleanField(default=False)),
                ('causa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Ordenes de Pagos',
            },
        ),
        migrations.CreateModel(
            name='OrdenPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('anio', models.CharField(max_length=4)),
                ('orden_pago', models.IntegerField()),
                ('descripcion', models.CharField(max_length=300)),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=4, max_digits=22)),
                ('saldo', models.DecimalField(decimal_places=4, max_digits=22)),
                ('monto_deduciones', models.DecimalField(decimal_places=4, max_digits=22)),
                ('saldo_deducciones', models.DecimalField(decimal_places=4, max_digits=22)),
                ('estatus', models.IntegerField(choices=[(0, 'Elaborada'), (1, 'Verificada'), (2, 'Anulada'), (3, 'Pagada'), (4, 'Reversada')], default=0, verbose_name='Estatus Orden')),
                ('contador', models.IntegerField(default=1)),
                ('anticipo_contrato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_pago', to='compras.anticipocontrato')),
                ('anulador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='anulador_ordenes_pago', to=settings.AUTH_USER_MODEL)),
                ('beneficiario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_pago', to='compras.beneficiario')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_pago', to='ejecucion.claseordenpago')),
                ('documento_pagar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_pago', to='compras.documentopagar')),
                ('elaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elaborador_ordenes_pago', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ordenes de Pago',
            },
        ),
    ]
