# Generated by Django 3.1.3 on 2021-02-18 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contabilidad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compras', '0001_initial'),
        ('formulacion', '0019_partida_publicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaseOrdenPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Clases de Ordenes de Pagos',
            },
        ),
        migrations.CreateModel(
            name='DocumentoPagar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('anio', models.CharField(max_length=4)),
                ('numero', models.CharField(max_length=10)),
                ('numero_control', models.CharField(max_length=10)),
                ('fecha', models.DateField()),
                ('monto_imponible', models.DecimalField(decimal_places=4, max_digits=22)),
                ('monto_iva', models.DecimalField(decimal_places=4, max_digits=22)),
                ('monto', models.DecimalField(decimal_places=4, max_digits=22)),
                ('descripcion', models.CharField(max_length=100)),
                ('compromiso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='compras.compromiso')),
            ],
            options={
                'verbose_name_plural': 'Documentos a Pagar',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('codigo', models.CharField(max_length=2)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Documentos',
            },
        ),
        migrations.CreateModel(
            name='TipoOrdenPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('codigo', models.CharField(max_length=3)),
                ('descripcion', models.CharField(max_length=100)),
                ('compromete', models.BooleanField(default=False)),
                ('causa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Ordenes de Pagos',
            },
        ),
        migrations.CreateModel(
            name='OrdenPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('anio', models.CharField(max_length=4)),
                ('orden_pago', models.IntegerField()),
                ('monto', models.DecimalField(decimal_places=4, max_digits=22)),
                ('descripcion', models.CharField(max_length=300)),
                ('fecha', models.DateField()),
                ('monto_imponible', models.DecimalField(decimal_places=4, max_digits=22, null=True)),
                ('saldo', models.DecimalField(decimal_places=4, max_digits=22)),
                ('monto_deduciones', models.DecimalField(decimal_places=4, max_digits=22)),
                ('saldo_deducciones', models.DecimalField(decimal_places=4, max_digits=22)),
                ('estatus', models.IntegerField(choices=[(0, 'Elaborada'), (1, 'Verificada'), (2, 'Anulada'), (3, 'Pagada'), (4, 'Reversada')], default=0, verbose_name='Estatus Orden')),
                ('contador', models.IntegerField(default=1)),
                ('anulador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anulador_ordenes_pago', to=settings.AUTH_USER_MODEL)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_pago', to='compras.beneficiario')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_pago', to='ejecucion.claseordenpago')),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_pago', to='contabilidad.comprobante')),
                ('comprobante_reverso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reverso_ordenes_pago', to='contabilidad.comprobante')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_pago', to='ejecucion.documentopagar')),
                ('elaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elaborador_ordenes_pago', to=settings.AUTH_USER_MODEL)),
                ('fuente_financiamiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_pagos', to='formulacion.fuentefinanciamiento')),
                ('reversor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisor_ordenes_pago', to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_pago', to='ejecucion.tipoordenpago')),
                ('unidad_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_pagos', to='formulacion.departamento')),
                ('verificador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verificador_ordenes_pago', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ordenes de Pago',
            },
        ),
        migrations.AddField(
            model_name='documentopagar',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='ejecucion.tipodocumento'),
        ),
        migrations.CreateModel(
            name='DetalleOrdenPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('tipo_afectacion', models.CharField(choices=[('D', 'Débito'), ('C', 'Crédito')], default='D', max_length=1)),
                ('monto', models.DecimalField(decimal_places=4, max_digits=22)),
                ('saldo', models.DecimalField(decimal_places=4, max_digits=22)),
                ('fecha', models.DateField()),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_ordenes_pago', to='contabilidad.comprobante')),
                ('cuenta_contable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_ordenes_pago', to='contabilidad.cuentacontable')),
                ('orden_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_ordenes_pagos', to='ejecucion.ordenpago')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_ordenes_pago', to='formulacion.partida')),
            ],
            options={
                'verbose_name_plural': 'Detalles de Ordenes de Pago',
            },
        ),
        migrations.CreateModel(
            name='DeduccionOrdenPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('monto', models.DecimalField(decimal_places=4, max_digits=22)),
                ('saldo', models.DecimalField(decimal_places=4, max_digits=22)),
                ('cuenta_contable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deducciones', to='contabilidad.cuentacontable')),
                ('orden_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deducciones', to='ejecucion.ordenpago')),
            ],
            options={
                'verbose_name_plural': 'Deducciones',
            },
        ),
    ]
