# Generated by Django 3.1.3 on 2021-03-05 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formulacion', '0001_initial'),
        ('planificacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('rif', models.CharField(max_length=12)),
                ('razon_social', models.CharField(max_length=100)),
                ('siglas', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=500)),
                ('telefono', models.CharField(max_length=13)),
                ('correo', models.EmailField(max_length=254)),
                ('numero_inscripcion', models.IntegerField()),
                ('fecha_inscripcion', models.DateField()),
                ('numero_registro', models.CharField(max_length=12)),
                ('fecha_registro', models.DateField()),
                ('capital', models.DecimalField(decimal_places=4, max_digits=22)),
                ('representante', models.CharField(max_length=100)),
                ('cedula_representante', models.CharField(max_length=12)),
                ('fecha_vigencia', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Beneficiarios',
            },
        ),
        migrations.CreateModel(
            name='ClaseOrdenPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Clases de Ordenes de Pagos',
            },
        ),
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('cuenta', models.CharField(max_length=12, unique=True)),
                ('descripcion', models.TextField(max_length=100)),
                ('nivel', models.IntegerField()),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_contables_ejecucion', to='formulacion.publicacion')),
            ],
            options={
                'verbose_name_plural': 'Cuentas Contables',
                'ordering': ('-creado',),
            },
        ),
        migrations.CreateModel(
            name='DocumentoPagar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('anio', models.CharField(max_length=4)),
                ('numero', models.CharField(max_length=10)),
                ('numero_control', models.CharField(max_length=10)),
                ('fecha', models.DateField()),
                ('monto_imponible', models.DecimalField(decimal_places=4, max_digits=22)),
                ('monto_iva', models.DecimalField(decimal_places=4, max_digits=22)),
                ('monto', models.DecimalField(decimal_places=4, max_digits=22)),
                ('descripcion', models.CharField(max_length=100)),
                ('forma_pago', models.IntegerField(choices=[(1, 'Crédito'), (2, 'Contado'), (3, 'Efectivo')], default=1)),
                ('beneficiario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_pagar_ejecucion', to='ejecucion.beneficiario')),
            ],
            options={
                'verbose_name_plural': 'Documentos a Pagar',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('codigo', models.CharField(max_length=4)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Documentos',
            },
        ),
        migrations.CreateModel(
            name='TipoOrdenPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('codigo', models.CharField(max_length=3)),
                ('descripcion', models.CharField(max_length=100)),
                ('compromete', models.BooleanField(default=False)),
                ('causa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Ordenes de Pagos',
            },
        ),
        migrations.CreateModel(
            name='TipoBeneficiario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('abreviacion', models.CharField(max_length=3)),
                ('descripcion', models.CharField(max_length=100)),
                ('cuenta_contable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipos_beneficiarios', to='ejecucion.cuentacontable')),
            ],
            options={
                'verbose_name_plural': 'Tipos de Beneficiarios',
            },
        ),
        migrations.CreateModel(
            name='OrdenPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('anio', models.CharField(max_length=4)),
                ('orden_pago', models.IntegerField()),
                ('descripcion', models.CharField(max_length=300)),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=4, max_digits=22)),
                ('saldo', models.DecimalField(decimal_places=4, max_digits=22)),
                ('monto_deduciones', models.DecimalField(decimal_places=4, max_digits=22)),
                ('saldo_deducciones', models.DecimalField(decimal_places=4, max_digits=22)),
                ('estatus', models.IntegerField(choices=[(0, 'Elaborada'), (1, 'Verificada'), (2, 'Anulada'), (3, 'Pagada'), (4, 'Reversada')], default=0, verbose_name='Estatus Orden')),
                ('contador', models.IntegerField(default=1)),
                ('anulador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='anulador_ordenes_pago', to=settings.AUTH_USER_MODEL)),
                ('beneficiario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_pago', to='ejecucion.beneficiario')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_pago', to='ejecucion.claseordenpago')),
                ('documento_pagar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_pago', to='ejecucion.documentopagar')),
                ('elaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elaborador_ordenes_pago', to=settings.AUTH_USER_MODEL)),
                ('fuente_financiamiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_pagos', to='formulacion.fuentefinanciamiento')),
                ('reversor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisor_ordenes_pago', to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_pago', to='ejecucion.tipoordenpago')),
                ('unidad_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_pagos', to='formulacion.departamento')),
                ('verificador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verificador_ordenes_pago', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ordenes de Pago',
            },
        ),
        migrations.CreateModel(
            name='Modificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('anio', models.CharField(max_length=4)),
                ('numero', models.CharField(max_length=10)),
                ('documento_referenciado', models.IntegerField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=22)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True)),
                ('descripcion', models.CharField(max_length=300)),
                ('partida_accioninterna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modificaciones_ejecucion', to='formulacion.partidaaccioninterna')),
                ('tipo_modificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modificaciones_ejecucion', to='planificacion.tipomodificacion')),
            ],
            options={
                'verbose_name_plural': 'Modificaciones',
            },
        ),
        migrations.AddField(
            model_name='documentopagar',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_pagar', to='ejecucion.tipodocumento'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='cuenta_anticipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anticipo_beneficiarios_ejecucion', to='ejecucion.cuentacontable'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='cuenta_contable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuenta_beneficiarios_ejecucion', to='ejecucion.cuentacontable'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='parroquia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beneficiarios_ejecucion', to='formulacion.parroquia'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='tipo_beneficiario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beneficiarios_ejecucion', to='ejecucion.tipobeneficiario'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='usuario_inscripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beneficiarios_ejecucion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AsientoContable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('tipo_afectacion', models.CharField(choices=[('D', 'Débito'), ('C', 'Crédito')], default='D', max_length=1)),
                ('monto', models.DecimalField(decimal_places=4, max_digits=22)),
                ('saldo', models.DecimalField(decimal_places=4, max_digits=22)),
                ('fecha', models.DateField()),
                ('cuenta_contable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asientos_contables_ejecucion', to='ejecucion.cuentacontable')),
                ('orden_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asientos_contables_ejecucion', to='ejecucion.ordenpago')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asientos_contables_ejecucion', to='formulacion.partidaaccioninterna')),
            ],
            options={
                'verbose_name_plural': 'Asientos Contables',
            },
        ),
        migrations.AlterUniqueTogether(
            name='documentopagar',
            unique_together={('numero', 'anio', 'beneficiario')},
        ),
    ]
