# Generated by Django 3.1.3 on 2021-04-09 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formulacion', '0001_initial'),
        ('nucleo', '0001_initial'),
        ('ejecucion', '0001_initial'),
        ('compras', '0003_auto_20210409_1707'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contabilidad', '0002_auto_20210409_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenpago',
            name='fuente_financiamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_pagos', to='formulacion.fuentefinanciamiento'),
        ),
        migrations.AddField(
            model_name='ordenpago',
            name='reversor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisor_ordenes_pago', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordenpago',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_pago', to='ejecucion.tipoordenpago'),
        ),
        migrations.AddField(
            model_name='ordenpago',
            name='unidad_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_pagos', to='formulacion.departamento'),
        ),
        migrations.AddField(
            model_name='ordenpago',
            name='valuacion_contrato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_pago', to='compras.valuacioncontrato'),
        ),
        migrations.AddField(
            model_name='ordenpago',
            name='verificador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verificador_ordenes_pago', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='afectacionpresupuestaria',
            name='asiento_contable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='afectaciones_presupuestarias', to='contabilidad.asientocontable'),
        ),
        migrations.AddField(
            model_name='afectacionpresupuestaria',
            name='movimiento_gasto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='afectaciones_presupuestarias', to='nucleo.movimientogasto'),
        ),
        migrations.AddField(
            model_name='afectacionpresupuestaria',
            name='orden_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='afectaciones_presupuestarias', to='ejecucion.ordenpago'),
        ),
        migrations.AddField(
            model_name='afectacioncontrato',
            name='asiento_contable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='afectaciones_contratos', to='contabilidad.asientocontable'),
        ),
        migrations.AddField(
            model_name='afectacioncontrato',
            name='contrato_partida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='afectaciones_contratos', to='compras.contratopartida'),
        ),
        migrations.AddField(
            model_name='afectacioncontrato',
            name='orden_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='afectaciones_contratos', to='ejecucion.ordenpago'),
        ),
    ]
