# Generated by Django 3.1.3 on 2021-02-24 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ejecucion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenpago',
            name='anulador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='anulador_ordenes_pago', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordenpago',
            name='reversor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisor_ordenes_pago', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordenpago',
            name='verificador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verificador_ordenes_pago', to=settings.AUTH_USER_MODEL),
        ),
    ]
