# Generated by Django 3.1.3 on 2021-03-05 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulacion', '0001_initial'),
        ('planificacion', '0001_initial'),
        ('ejecucion', '0002_auto_20210305_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('anio', models.CharField(max_length=4)),
                ('numero', models.CharField(max_length=10)),
                ('documento_referenciado', models.IntegerField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=22)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True)),
                ('descripcion', models.CharField(max_length=300)),
                ('partida_accioninterna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modificaciones_ejecucion', to='formulacion.partidaaccioninterna')),
                ('tipo_modificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modificaciones_ejecucion', to='planificacion.tipomodificacion')),
            ],
            options={
                'verbose_name_plural': 'Modificaciones',
            },
        ),
    ]
