# Generated by Django 3.1.3 on 2021-02-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('mes', models.CharField(max_length=2)),
                ('anio', models.CharField(max_length=4)),
                ('codigo', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=4, max_digits=22)),
            ],
            options={
                'verbose_name_plural': 'Comprobantes',
                'unique_together': {('mes', 'anio', 'codigo')},
            },
        ),
    ]
