# Generated by Django 3.1.3 on 2021-02-23 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formulacion', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('cuenta', models.CharField(max_length=12, unique=True)),
                ('descripcion', models.TextField(max_length=100)),
                ('nivel', models.IntegerField()),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_contables', to='formulacion.publicacion')),
            ],
            options={
                'verbose_name_plural': 'Cuentas Contables',
                'ordering': ('-creado',),
            },
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('periodo', models.CharField(max_length=2)),
                ('anio', models.CharField(max_length=4)),
                ('codigo', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=4, max_digits=22)),
            ],
            options={
                'verbose_name_plural': 'Comprobantes',
                'unique_together': {('periodo', 'anio', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='AsientoContable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('tipo_afectacion', models.CharField(choices=[('D', 'Débito'), ('C', 'Crédito')], default='D', max_length=1)),
                ('monto', models.DecimalField(decimal_places=4, max_digits=22)),
                ('saldo', models.DecimalField(decimal_places=4, max_digits=22)),
                ('fecha', models.DateField()),
                ('cuenta_contable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asientos_contables', to='contabilidad.cuentacontable')),
            ],
            options={
                'verbose_name_plural': 'Asientos Contables',
            },
        ),
    ]
