# Generated by Django 3.1.3 on 2021-02-23 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formulacion', '__first__'),
        ('contabilidad', '0001_initial'),
        ('ejecucion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asientocontable',
            name='orden_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asientos_contables', to='ejecucion.ordenpago'),
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='partida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asientos_contables', to='formulacion.partidaaccioninterna'),
        ),
    ]
