# Generated by Django 3.1.3 on 2021-04-09 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contabilidad', '0001_initial'),
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentacontable',
            name='publicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_contables', to='nucleo.publicacion'),
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='cuenta_contable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asientos_contables', to='contabilidad.cuentacontable'),
        ),
        migrations.AlterUniqueTogether(
            name='cuentacontable',
            unique_together={('periodo', 'anio', 'codigo')},
        ),
    ]
