# Generated by Django 3.1.3 on 2021-03-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partidaaccioninterna',
            name='condicion_ejercicio',
            field=models.IntegerField(choices=[(0, 'Formulación'), (1, 'Ejecución')], default=0, verbose_name='Condición del Ejercicio'),
        ),
    ]
