# Generated by Django 3.1.3 on 2021-02-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EjercicioPresupuestario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('anio', models.CharField(max_length=4)),
                ('condicion', models.IntegerField(choices=[(0, 'Formulación'), (1, 'Ejecución'), (2, 'Complementario'), (3, 'Cerrado')], default=0, verbose_name='Condición de Ejercicio Presupuestario')),
            ],
            options={
                'verbose_name_plural': 'Ejercicios Presupuestarios',
                'unique_together': {('anio',)},
            },
        ),
    ]
