# Generated by Django 3.1.3 on 2020-12-23 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulacion', '0002_auto_20201223_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadejecutora',
            name='adscrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='formulacion.unidadejecutora'),
        ),
    ]
