# Generated by Django 3.1.3 on 2020-12-04 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulacion', '0002_auto_20201203_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='estatus',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='partida',
            name='saldo',
            field=models.DecimalField(decimal_places=4, max_digits=22, null=True),
        ),
    ]
