# Generated by Django 3.1.3 on 2021-02-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulacion', '0002_ejerciciopresupuestario'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='beneficiario_femenino',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programa',
            name='beneficiario_masculino',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programa',
            name='beneficiario_total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
