# Generated by Django 3.1.3 on 2021-03-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulacion', '0002_partidaaccioninterna_condicion_ejercicio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClaseIngreso',
        ),
        migrations.RemoveField(
            model_name='modificacioningreso',
            name='anulador',
        ),
        migrations.RemoveField(
            model_name='modificacioningreso',
            name='elaborador',
        ),
        migrations.RemoveField(
            model_name='modificacioningreso',
            name='partida',
        ),
        migrations.RemoveField(
            model_name='modificacioningreso',
            name='verificador',
        ),
        migrations.AddField(
            model_name='dependencia',
            name='mision',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dependencia',
            name='politica',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dependencia',
            name='vision',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
    ]
