# Generated by Django 3.1.3 on 2020-12-06 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulacion', '0003_auto_20201204_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='cuenta',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
