# Generated by Django 3.1.3 on 2021-03-11 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulacion', '0003_auto_20210311_1711'),
        ('planificacion', '0002_auto_20210311_1711'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModificacionIngreso',
        ),
    ]
