# Generated by Django 3.1.3 on 2021-02-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulacion', '0003_auto_20210224_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='indicador_formula',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programa',
            name='indicador_fuente',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programa',
            name='indicador_objetivo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programa',
            name='indicador_situacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programa',
            name='sexo_beneficiario',
            field=models.IntegerField(choices=[(0, 'Femenino'), (1, 'Masculino'), (2, 'Ambos'), (3, 'No Definido')], default=3, verbose_name='Sexo del Beneficiario'),
        ),
    ]
