# Generated by Django 3.1.3 on 2020-12-24 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulacion', '0003_auto_20201223_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='dependencia',
        ),
        migrations.AlterField(
            model_name='unidadejecutora',
            name='adscrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidadejecutoras', to='formulacion.unidadejecutora'),
        ),
    ]
