# Generated by Django 3.1.3 on 2021-01-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulacion', '0004_auto_20201224_1425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centrocosto',
            options={'ordering': ('-creado',), 'verbose_name_plural': 'Centros de Costos'},
        ),
        migrations.RenameField(
            model_name='programa',
            old_name='detallada',
            new_name='detalle',
        ),
        migrations.RemoveField(
            model_name='programa',
            name='beneficiario_femenino',
        ),
        migrations.RemoveField(
            model_name='programa',
            name='beneficiario_masculino',
        ),
        migrations.RemoveField(
            model_name='programa',
            name='dependencia',
        ),
        migrations.RemoveField(
            model_name='programa',
            name='distincion_genero',
        ),
        migrations.AddField(
            model_name='programa',
            name='sexo_benificiario',
            field=models.IntegerField(choices=[(0, 'Femenino'), (1, 'Masculino'), (2, 'No Definido')], default=2, verbose_name='Sexo del Beneficiario'),
        ),
        migrations.AlterField(
            model_name='centrocosto',
            name='codigo',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
