# Generated by Django 3.1.3 on 2020-12-07 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulacion', '0004_auto_20201206_1903'),
        ('formulacion', '0003_auto_20201204_1631'),
    ]

    operations = [
    ]
