# Generated by Django 3.1.3 on 2021-02-24 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulacion', '0004_auto_20210224_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineaprograma',
            name='auxiliar',
        ),
    ]
