# Generated by Django 3.1.3 on 2021-02-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulacion', '0005_remove_lineaprograma_auxiliar'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineaprograma',
            name='auxiliar',
            field=models.IntegerField(default=1),
        ),
    ]
