# Generated by Django 3.1.3 on 2021-02-25 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulacion', '0006_lineaprograma_auxiliar'),
    ]

    operations = [
        migrations.AddField(
            model_name='accionespecifica',
            name='beneficiario_femenino',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accionespecifica',
            name='beneficiario_masculino',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accionespecifica',
            name='beneficiario_total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accionespecifica',
            name='sexo_beneficiario',
            field=models.IntegerField(choices=[(0, 'Femenino'), (1, 'Masculino'), (2, 'Ambos'), (3, 'No Definido')], default=2, verbose_name='Sexo del Beneficiario'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='sexo_beneficiario',
            field=models.IntegerField(choices=[(0, 'Femenino'), (1, 'Masculino'), (2, 'Ambos'), (3, 'No Definido')], default=2, verbose_name='Sexo del Beneficiario'),
        ),
    ]
