# Generated by Django 3.1.3 on 2021-01-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulacion', '0006_auto_20210104_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='programa',
            name='inicio',
            field=models.DateField(),
        ),
    ]
