# Generated by Django 3.1.3 on 2021-01-05 11:55

from django.db import migrations, models
from datetime import timedelta


class Migration(migrations.Migration):

    dependencies = [
        ('formulacion', '0007_auto_20210104_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='contador',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programa',
            name='duracion',
            field=models.DurationField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dependencia',
            name='codigo',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='programa',
            name='nivel',
            field=models.IntegerField(choices=[(1, 'Proyecto'), (2, 'Acción Centralizada')]),
        ),
        migrations.AlterField(
            model_name='sector',
            name='codigo',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='programa',
            unique_together={('anio', 'nivel', 'contador')},
        ),
    ]
