# Generated by Django 3.1.3 on 2021-01-08 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulacion', '0008_auto_20210105_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accionespecifica',
            name='beneficiario_femenino',
        ),
        migrations.RemoveField(
            model_name='accionespecifica',
            name='beneficiario_masculino',
        ),
        migrations.RemoveField(
            model_name='accionespecifica',
            name='distincion_genero',
        ),
        migrations.AddField(
            model_name='accionespecifica',
            name='contador',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='accionespecifica',
            name='duracion',
            field=models.DurationField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accionespecifica',
            name='sexo_beneficiario',
            field=models.IntegerField(choices=[(0, 'Femenino'), (1, 'Masculino'), (2, 'No Definido')], default=2, verbose_name='Sexo del Beneficiario'),
        ),
        migrations.AlterField(
            model_name='accionespecifica',
            name='condicion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acciones_especificas', to='formulacion.condicionprograma'),
        ),
        migrations.AlterField(
            model_name='accionespecifica',
            name='fecha_aprobacion_f_e',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='accionespecifica',
            name='fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='accionespecifica',
            name='financiamiento_externo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='accionespecifica',
            name='inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='accionespecifica',
            name='inicio_ejecucion_fisica_f_e',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tipoareainversion',
            name='codigo',
            field=models.CharField(max_length=7),
        ),
    ]
