# Generated by Django 3.1.3 on 2021-02-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulacion', '0008_auto_20210225_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accionespecifica',
            name='articulacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accionespecifica',
            name='detallada',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accionespecifica',
            name='especifico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accionespecifica',
            name='impacto_social',
            field=models.TextField(blank=True, null=True),
        ),
    ]
