# Generated by Django 3.1.3 on 2021-01-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulacion', '0009_auto_20210108_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accionespecifica',
            name='ejecutado_anio_anterior',
            field=models.DecimalField(decimal_places=2, max_digits=22),
        ),
        migrations.AlterField(
            model_name='accionespecifica',
            name='estimado_anio_ejercicio',
            field=models.DecimalField(decimal_places=2, max_digits=22),
        ),
        migrations.AlterField(
            model_name='accionespecifica',
            name='estimado_anio_siguiente',
            field=models.DecimalField(decimal_places=2, max_digits=22),
        ),
        migrations.AlterField(
            model_name='accionespecifica',
            name='trimestre_1',
            field=models.DecimalField(decimal_places=2, max_digits=22),
        ),
        migrations.AlterField(
            model_name='accionespecifica',
            name='trimestre_2',
            field=models.DecimalField(decimal_places=2, max_digits=22),
        ),
        migrations.AlterField(
            model_name='accionespecifica',
            name='trimestre_3',
            field=models.DecimalField(decimal_places=2, max_digits=22),
        ),
        migrations.AlterField(
            model_name='accionespecifica',
            name='trimestre_4',
            field=models.DecimalField(decimal_places=2, max_digits=22),
        ),
        migrations.AlterField(
            model_name='ctasccostoaint',
            name='mto_actualizado',
            field=models.DecimalField(decimal_places=2, max_digits=22),
        ),
        migrations.AlterField(
            model_name='ctasccostoaint',
            name='mto_original',
            field=models.DecimalField(decimal_places=2, max_digits=22),
        ),
        migrations.AlterField(
            model_name='estimacion',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=22),
        ),
        migrations.AlterField(
            model_name='partida',
            name='saldo',
            field=models.DecimalField(decimal_places=2, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='programa',
            name='trimestre_1',
            field=models.DecimalField(decimal_places=2, max_digits=22),
        ),
        migrations.AlterField(
            model_name='programa',
            name='trimestre_2',
            field=models.DecimalField(decimal_places=2, max_digits=22),
        ),
        migrations.AlterField(
            model_name='programa',
            name='trimestre_3',
            field=models.DecimalField(decimal_places=2, max_digits=22),
        ),
        migrations.AlterField(
            model_name='programa',
            name='trimestre_4',
            field=models.DecimalField(decimal_places=2, max_digits=22),
        ),
    ]
