# Generated by Django 3.1.3 on 2021-02-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulacion', '0009_auto_20210225_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='accioninterna',
            name='auxiliar_inv',
            field=models.IntegerField(default=1),
        ),
    ]
