# Generated by Django 3.1.3 on 2021-03-05 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulacion', '0010_accioninterna_auxiliar_inv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='publicacion',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='partidas', to='formulacion.publicacion'),
        ),
    ]
