# Generated by Django 3.1.3 on 2021-03-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulacion', '0010_accioninterna_auxiliar_inv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejerciciopresupuestario',
            name='condicion',
            field=models.IntegerField(choices=[(0, 'Formulación'), (1, 'Ejecución'), (2, 'Complementario'), (3, 'Cerrado'), (4, 'Creado')], verbose_name='Condición de Ejercicio Presupuestario'),
        ),
        migrations.AlterUniqueTogether(
            name='ejerciciopresupuestario',
            unique_together={('anio', 'eliminado')},
        ),
        migrations.AlterUniqueTogether(
            name='estimacion',
            unique_together={('accion_especifica', 'partida', 'anio', 'eliminado')},
        ),
    ]
