# Generated by Django 3.1.3 on 2021-01-21 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulacion', '0012_auto_20210121_1540'),
        ('planificacion', '0002_auto_20210121_1540'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CtasCCostoAInt',
        ),
        migrations.AddField(
            model_name='partidaaccioninterna',
            name='accion_interna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partida_accioninternas', to='formulacion.accioninterna'),
        ),
        migrations.AddField(
            model_name='partidaaccioninterna',
            name='partida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partida_accioninternas', to='formulacion.partida'),
        ),
        migrations.AlterUniqueTogether(
            name='partidaaccioninterna',
            unique_together={('accion_interna', 'partida', 'anio')},
        ),
    ]
