# Generated by Django 3.1.3 on 2021-01-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulacion', '0013_auto_20210121_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipogasto',
            options={'verbose_name_plural': 'Tipos de Gastos'},
        ),
        migrations.AlterField(
            model_name='accioninterna',
            name='auxiliar',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='programa',
            name='contador',
            field=models.IntegerField(default=1),
        ),
    ]
