# Generated by Django 3.1.3 on 2021-01-22 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulacion', '0014_auto_20210122_1615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partidaaccioninterna',
            options={'verbose_name_plural': 'Cuentas - Acciones Internas'},
        ),
    ]
