# Generated by Django 3.1.3 on 2021-01-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulacion', '0015_auto_20210122_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineaprograma',
            name='auxiliar',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='plandesarrollo',
            name='auxiliar',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='lineaplan',
            name='codigo',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='lineaprograma',
            name='codigo',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='plandesarrollo',
            name='codigo',
            field=models.CharField(max_length=4),
        ),
    ]
