# Generated by Django 3.1.3 on 2021-02-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulacion', '0016_auto_20210124_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('codigo', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
                ('anio', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name_plural': 'Publicaciones',
            },
        ),
    ]
