# Generated by Django 3.1.3 on 2021-02-08 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulacion', '0017_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accionespecifica',
            name='estatus_financiamiento_externo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acciones_especificas', to='formulacion.estatusfinanciamientoexterno'),
        ),
        migrations.AlterField(
            model_name='accionespecifica',
            name='fase',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='accionespecifica',
            name='parroquia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acciones_especificas', to='formulacion.parroquia'),
        ),
        migrations.AlterField(
            model_name='accionespecifica',
            name='tipo_area_inversion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acciones_especificas', to='formulacion.tipoareainversion'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='saldo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True),
        ),
    ]
