# Generated by Django 3.1.3 on 2021-02-12 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulacion', '0018_auto_20210208_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='publicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidas', to='formulacion.publicacion'),
            preserve_default=False,
        ),
    ]
