# Generated by Django 3.1.3 on 2021-01-13 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formulacion', '0010_auto_20210113_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('codigo', models.CharField(max_length=3)),
                ('nombre_corto', models.CharField(max_length=20)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('rif', models.CharField(max_length=12)),
                ('direccion', models.CharField(max_length=500)),
                ('codigo_postal', models.CharField(max_length=5)),
                ('persona_contacto', models.CharField(max_length=100)),
                ('telefono_contacto', models.CharField(max_length=13)),
                ('correo', models.EmailField(max_length=254)),
                ('fax', models.CharField(max_length=12)),
                ('condicion', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Bancos',
            },
        ),
        migrations.CreateModel(
            name='CodigoContable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('codigo', models.CharField(max_length=3)),
                ('tipo', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Códigos Contables',
            },
        ),
        migrations.CreateModel(
            name='TipoCuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('codigo', models.CharField(max_length=2)),
                ('descripcion', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Cuentas Bancarias',
            },
        ),
        migrations.CreateModel(
            name='TiposDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('codigo', models.CharField(max_length=2)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('tipo_afectacion', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Documentos',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('nombre', models.CharField(max_length=100)),
                ('siglas', models.CharField(max_length=20)),
                ('rif', models.CharField(max_length=12)),
                ('direccion', models.CharField(max_length=500)),
                ('codigo_postal', models.CharField(max_length=5)),
                ('telefono', models.CharField(max_length=13)),
                ('correo', models.EmailField(max_length=254)),
                ('repr_legal', models.CharField(max_length=100)),
                ('rif_repr_legal', models.CharField(max_length=12)),
                ('parroquia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proveedores', to='formulacion.parroquia')),
            ],
            options={
                'verbose_name_plural': 'proveedores',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('anio', models.CharField(max_length=4)),
                ('numero', models.CharField(max_length=10)),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=4, max_digits=22)),
                ('saldo', models.DecimalField(decimal_places=4, max_digits=22)),
                ('descripcion', models.CharField(max_length=100)),
                ('cta_ccosto_accint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='formulacion.ctasccostoaint')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='planificacion.proveedor')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='planificacion.tiposdocumento')),
            ],
            options={
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='CuentaProveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('numero', models.CharField(max_length=20)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentaproveedores', to='planificacion.banco')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentaproveedores', to='planificacion.proveedor')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentaproveedores', to='planificacion.tipocuenta')),
            ],
            options={
                'verbose_name_plural': 'Cuentas Bancarias de proveedores',
            },
        ),
        migrations.AddField(
            model_name='banco',
            name='codigo_contable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Bancos', to='planificacion.codigocontable'),
        ),
        migrations.AddField(
            model_name='banco',
            name='parroquia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Bancos', to='formulacion.parroquia'),
        ),
        migrations.CreateModel(
            name='AcumuladosPresupuestario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('anio', models.CharField(max_length=4)),
                ('mes', models.CharField(max_length=2)),
                ('compromiso', models.DecimalField(decimal_places=4, max_digits=22)),
                ('causado', models.DecimalField(decimal_places=4, max_digits=22)),
                ('pago', models.DecimalField(decimal_places=4, max_digits=22)),
                ('aumento', models.DecimalField(decimal_places=4, max_digits=22)),
                ('disminucion', models.DecimalField(decimal_places=4, max_digits=22)),
                ('por_comprometer', models.DecimalField(decimal_places=4, max_digits=22)),
                ('por_causar', models.DecimalField(decimal_places=4, max_digits=22)),
                ('por_pagar', models.DecimalField(decimal_places=4, max_digits=22)),
                ('monto', models.DecimalField(decimal_places=4, max_digits=22)),
                ('saldo', models.DecimalField(decimal_places=4, max_digits=22)),
                ('descripcion', models.CharField(max_length=100)),
                ('cta_ccosto_accint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acumuladospresupuestarios', to='formulacion.ctasccostoaint')),
            ],
            options={
                'verbose_name_plural': 'Acumulados Presupuestario',
                'unique_together': {('cta_ccosto_accint', 'mes', 'anio')},
            },
        ),
    ]
