# Generated by Django 3.1.3 on 2021-02-23 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formulacion', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoModificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('codigo', models.CharField(max_length=2)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('tipo_afectacion', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Modificaciones',
            },
        ),
        migrations.CreateModel(
            name='Modificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('anio', models.CharField(max_length=4)),
                ('numero', models.CharField(max_length=10)),
                ('documento_referenciado', models.IntegerField()),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=4, max_digits=22)),
                ('saldo', models.DecimalField(decimal_places=4, max_digits=22)),
                ('descripcion', models.CharField(max_length=300)),
                ('partida_accioninterna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='formulacion.partidaaccioninterna')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='planificacion.tipomodificacion')),
            ],
            options={
                'verbose_name_plural': 'Modificaciones',
            },
        ),
        migrations.CreateModel(
            name='AcumuladosPresupuestario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('anio', models.CharField(max_length=4)),
                ('mes', models.CharField(max_length=2)),
                ('compromiso', models.DecimalField(decimal_places=4, max_digits=22)),
                ('causado', models.DecimalField(decimal_places=4, max_digits=22)),
                ('pago', models.DecimalField(decimal_places=4, max_digits=22)),
                ('aumento', models.DecimalField(decimal_places=4, max_digits=22)),
                ('disminucion', models.DecimalField(decimal_places=4, max_digits=22)),
                ('por_comprometer', models.DecimalField(decimal_places=4, max_digits=22)),
                ('por_causar', models.DecimalField(decimal_places=4, max_digits=22)),
                ('por_pagar', models.DecimalField(decimal_places=4, max_digits=22)),
                ('monto', models.DecimalField(decimal_places=4, max_digits=22)),
                ('saldo', models.DecimalField(decimal_places=4, max_digits=22)),
                ('descripcion', models.CharField(max_length=100)),
                ('partida_accioninterna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acumuladospresupuestarios', to='formulacion.partidaaccioninterna')),
            ],
            options={
                'verbose_name_plural': 'Acumulados Presupuestario',
                'unique_together': {('partida_accioninterna', 'mes', 'anio')},
            },
        ),
    ]
