# Generated by Django 3.1.3 on 2021-03-11 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formulacion', '0003_auto_20210311_1711'),
        ('planificacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaseIngreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('codigo', models.CharField(max_length=2)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('afectacion', models.CharField(choices=[('D', 'Disminucion'), ('A', 'Aumento')], max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Clases de Ingresos',
            },
        ),
        migrations.CreateModel(
            name='ModificacionIngreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('anio', models.CharField(max_length=4)),
                ('fecha', models.DateField()),
                ('periodo', models.CharField(max_length=2)),
                ('numero', models.IntegerField()),
                ('tipo_documento', models.IntegerField(choices=[(0, 'Gaceta'), (1, 'Acta')], verbose_name='Tipo de Documento del Ingreso')),
                ('numero_documento', models.CharField(max_length=10)),
                ('fecha_documento', models.DateField()),
                ('numero_decreto', models.CharField(max_length=10)),
                ('fecha_decreto', models.DateField()),
                ('descripcion', models.CharField(max_length=300)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=22)),
                ('estatus', models.IntegerField(choices=[(0, 'Elaborado'), (1, 'Verificado'), (2, 'Anulado')], default=0, verbose_name='Estatus Modificacón de Ingreso')),
                ('anulador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a_modificaciones_ingresos', to=settings.AUTH_USER_MODEL)),
                ('elaborador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='e_modificaciones_ingresos', to=settings.AUTH_USER_MODEL)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modificaciones_ingresos', to='formulacion.partida')),
                ('verificador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='v_modificaciones_ingresos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Modificaciones de Ingresos',
            },
        ),
        migrations.AlterField(
            model_name='modificacion',
            name='modificacion_ingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modificaciones', to='planificacion.modificacioningreso'),
        ),
    ]
