# Generated by Django 3.1.3 on 2021-03-08 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formulacion', '0002_claseingreso_modificacioningreso'),
        ('planificacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modificacion',
            name='anulador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a_modificaciones_egreso', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modificacion',
            name='elaborador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='e_modificaciones_egreso', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modificacion',
            name='estatus',
            field=models.IntegerField(choices=[(0, 'Elaborado'), (1, 'Verificado'), (2, 'Anulado')], default=0, verbose_name='Estatus Modificación de Egreso'),
        ),
        migrations.AddField(
            model_name='modificacion',
            name='modificacion_ingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modificaciones', to='formulacion.modificacioningreso'),
        ),
        migrations.AddField(
            model_name='modificacion',
            name='verificador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='v_modificaciones_egreso', to=settings.AUTH_USER_MODEL),
        ),
    ]
