# Generated by Django 3.1.3 on 2021-01-21 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulacion', '0012_auto_20210121_1540'),
        ('planificacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='cta_ccosto_accint',
        ),
        migrations.AddField(
            model_name='acumuladospresupuestario',
            name='partida_accioninterna',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='acumuladospresupuestarios', to='formulacion.partidaaccioninterna'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documento',
            name='partida_accioninterna',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='formulacion.partidaaccioninterna'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='acumuladospresupuestario',
            unique_together={('partida_accioninterna', 'mes', 'anio')},
        ),
        migrations.RemoveField(
            model_name='acumuladospresupuestario',
            name='cta_ccosto_accint',
        ),
    ]
