# Generated by Django 3.1.3 on 2021-02-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modificacion',
            name='fecha',
        ),
        migrations.AlterField(
            model_name='tipomodificacion',
            name='afectacion',
            field=models.CharField(choices=[('D', 'Disminucion'), ('A', 'Aumento')], max_length=1),
        ),
        migrations.AlterField(
            model_name='tipomodificacion',
            name='modificacion',
            field=models.CharField(choices=[('D', 'Disminucion'), ('A', 'Aumento'), ('T', 'Traspaso')], max_length=1),
        ),
    ]
