# Generated by Django 3.1.3 on 2021-03-22 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formulacion', '0004_delete_modificacioningreso'),
        ('planificacion', '0002_auto_20210311_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModificacionGasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('anio', models.CharField(max_length=4)),
                ('fecha', models.DateField()),
                ('periodo', models.CharField(max_length=2)),
                ('numero', models.IntegerField()),
                ('documento_referenciado', models.IntegerField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=22)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True)),
                ('descripcion', models.CharField(max_length=300)),
                ('estatus', models.IntegerField(choices=[(0, 'Elaborada'), (1, 'Verificada'), (2, 'Anulada')], default=0, verbose_name='Estatus Modificación de Gasto')),
                ('anulador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a_modificaciones_gastos', to=settings.AUTH_USER_MODEL)),
                ('elaborador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='e_modificaciones_gastos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Modificaciones de Gastos',
            },
        ),
        migrations.DeleteModel(
            name='ClaseIngreso',
        ),
        migrations.RemoveField(
            model_name='modificacioningreso',
            name='fecha_decreto',
        ),
        migrations.AddField(
            model_name='modificacioningreso',
            name='tipo_modificacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modificaciones_ingresos', to='planificacion.tipomodificacion'),
        ),
        migrations.AddField(
            model_name='tipomodificacion',
            name='tipo_modificacion',
            field=models.CharField(choices=[('I', 'Ingresos'), ('G', 'Gastos')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='modificacioningreso',
            name='descripcion',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='modificacioningreso',
            name='numero_decreto',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tipomodificacion',
            name='afectacion',
            field=models.CharField(choices=[('D', 'Disminucion'), ('A', 'Aumento'), ('T', 'Traspaso')], max_length=1),
        ),
        migrations.DeleteModel(
            name='Modificacion',
        ),
        migrations.AddField(
            model_name='modificaciongasto',
            name='modificacion_ingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modificaciones_gastos', to='planificacion.modificacioningreso'),
        ),
        migrations.AddField(
            model_name='modificaciongasto',
            name='partida_accioninterna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modificaciones_gastos', to='formulacion.partidaaccioninterna'),
        ),
        migrations.AddField(
            model_name='modificaciongasto',
            name='tipo_modificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modificaciones_gastos', to='planificacion.tipomodificacion'),
        ),
        migrations.AddField(
            model_name='modificaciongasto',
            name='verificador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='v_modificaciones_gastos', to=settings.AUTH_USER_MODEL),
        ),
    ]
