# Generated by Django 3.1.3 on 2021-02-05 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '__first__'),
        ('planificacion', '0002_auto_20210121_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentaproveedor',
            name='banco',
        ),
        migrations.RemoveField(
            model_name='cuentaproveedor',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='cuentaproveedor',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='parroquia',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='documento',
            name='beneficiario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='compras.beneficiario'),
        ),
        migrations.DeleteModel(
            name='Banco',
        ),
        migrations.DeleteModel(
            name='CodigoContable',
        ),
        migrations.DeleteModel(
            name='CuentaProveedor',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
        migrations.DeleteModel(
            name='TipoCuenta',
        ),
    ]
