# Generated by Django 3.1.3 on 2021-03-01 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0002_auto_20210225_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipomodificacion',
            name='modificacion',
        ),
        migrations.AlterField(
            model_name='modificacion',
            name='documento_referenciado',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modificacion',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=22),
        ),
        migrations.AlterField(
            model_name='modificacion',
            name='saldo',
            field=models.DecimalField(decimal_places=2, max_digits=22),
        ),
    ]
