# Generated by Django 3.1.3 on 2021-03-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0003_auto_20210301_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modificacion',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='modificacion',
            name='saldo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True),
        ),
    ]
